# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'Total' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.4'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Kingfisher', '~> 7.0'
  pod 'GradientButtonSwift'
  pod 'XHQWebViewJavascriptBridge'
  pod 'KakaoSDK'
  pod 'naveridlogin-sdk-ios'
  pod 'Socket.IO-Client-Swift', '~> 15.2.0'
  pod 'SDWebImageWebPCoder'
  pod 'lottie-ios'
  
  # Pods for Total

end
